#mods
import time
import subprocess
subprocess.run("ip address", shell=True)
startwow = input("Are these details correct?(y/n)")
if startwow == "y":
	#clearShellConfig
	clearCmd = "clear"
	#startScreenConfig
	subprocess.run(clearCmd, shell=True)
	print("ASPBL Python3      TxSearch BVPR1(BV0.1)")
	print("----------------------------------------")
	print()
	print()
	print()
	print("TxSearch version 0.1")
	time.sleep(1)
	#browserSelectionConfig
	subprocess.run(clearCmd, shell=True)
	print("TxSearch BV0.1      Browser Base Selection")
	print()
	print()
	print()
	print("Select a search engine:")
	print("Google(firefox)")
	print("Google(firefox--privite-window)")
	print("Brave(brave-browser)")
	print("Brave(brave-browser --incognito)")
	print("Tor(brave-browser --tor)")
	print()
	print("NOTE: Must have installed selected browser!")
	print()
	broSelect = input("NUMBER: ")
	#broSelectFireFoxConfig
	if broSelect == "1":
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input")
		print("Input URL for FireFox")
		url = input("URL: ")
		firefoxCmd = ("firefox " + url)
		firefoxFV = ("firefox --full-version")
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input / Connection Status")
		print()
		print()
		print()
		subprocess.run(firefoxFV, shell=True)
		subprocess.run(firefoxCmd, shell=True)
	#broSelectFireFoxIncognitoConfig
	if broSelect == "2":
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input")
		print()
		print()
		print()
		print("Input URL for FireFox")
		url = input("URL: ")
		firefoxCmdi = ("firefox --private-window " + url)
		firefoxFVi = ("firefox --full-version")
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input / Connection Status")
		print()
		print()
		print()
		subprocess.run(firefoxFVi, shell=True)
		subprocess.run(firefoxCmdi, shell=True)
	#broSelectBraveConfig
	if broSelect == "3":
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input")
		print()
		print()
		print()
		print("Input URL for Brave")
		url = input("URL: ")
		braveBrowserCmd = ("brave-browser " + url)
		braveBrowserV = ("brave-browser --version")
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input / Connection Status")
		print()
		print()
		print()
		subprocess.run(braveBrowserV, shell=True)
		subprocess.run(braveBrowserCmd, shell=True)
	#broSelectBraveIncognitoConfig
	if broSelect == "4":
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input")
		print()
		print()
		print()
		print("Input URL for Brave")
		url = input("URL: ")
		braveBrowserCmdi = ("brave-browser --incognito " + url)
		braveBrowserVi = ("brave-browser --version")
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input / Connection Status")
		print()
		print()
		print()
		subprocess.run(braveBrowserVi, shell=True)
		subprocess.run(braveBrowserCmdi, shell=True)
	#broSelectTorConfig
	if broSelect == "5":
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input")
		print()
		print()
		print()
		print("Input URL for Tor")
		url = input("URL: ")
		braveBrowserCmdTor = ("brave-browser --tor " + url)
		braveBrowserVTor = ("brave-browser --version")
		subprocess.run(clearCmd, shell=True)
		print("TxSearch BV0.1      Browser Selection / URL Input / Connection Status")
		print()
		print()
		print()
		subprocess.run(braveBrowserVTor, shell=True)
		subprocess.run(braveBrowserCmdTor, shell=True)
